from views.ats_view import ATSView
from views.pt_view import PTView
from views.preuso_view import PreusoView
from views.firma_view import FirmaView
from views.herramienta_view import HerramientaView
from views.epp_view import EPPView
from views.trabajador_view import TrabajadorView
from views.autorizador_view import AutorizadorView
from views.pregunta_pt_view import Pregunta_PTView 
from views.empresa_view import EmpresaView
from views.proyecto_view import ProyectoView
